[build]
  # Variáveis de ambiente que você deseja definir durante a construção
  [build.env]
    NODE_ENV = "production"

  # Dependências que serão instaladas durante a construção
  [build.dependencies]
    "@fortawesome/fontawesome-svg-core" = "^6.5.1"
    "autoprefixer" = "^10.4.17"
    "axios" = "^1.6.7"
    "body-parser" = "^1.20.2"
    "discord.js" = "^14.12.1"
    "dotenv" = "^16.3.1"
    "ejs" = "^3.1.9"
    "express" = "^4.18.2"
    "express-handlebars" = "^7.1.2"
    "express-session" = "^1.17.3"
    "font-awesome" = "^4.7.0"
    "googleapis" = "^129.0.0"
    "mongoose" = "^8.0.4"
    "passport" = "^0.7.0"
    "passport-discord" = "^0.1.4"
    "passport-oauth2-refresh" = "^2.2.0"
    "transition-style" = "^0.1.3"
    "watch" = "^0.13.0"
